version: '3.9'

services:
  stats:
    build: .
    command: sh ./entrypoint.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    networks:
      - innotter_default

  celery:
    restart: always
    build:
      context: .
    env_file:
      - ./.env
    command: sh ./run_celery.sh
    volumes:
      - .:/code
    depends_on:
      - stats
    networks:
      - innotter_default

networks:
  innotter_default:
    external: true
